---
title: "BIO 444 Test Questions"
output: html_notebook
---

# 1 Unix Loops
In order to run our migrate-n analyses we had to construct directories, each containing a parameter settings file, and then enter each directory to run migrate. Imagine that instead of 1 species, you had to analyze 40 species with migrate-n.

Write a 'for-loop' in unix that would allow you to start in a directory containing directories with all five hypotheses, move into each directory, start migrate-n, and then move to the next directory until migrate models are running in each directory.

Ignore the need to create virtual terminal windows (screen) for this problem: imagine that migrate-n starts in the background and then lets you issue more commands.

You may use the directory linked [here]() to experiment with. Give the code in the box below.

```{bash}
for dir in *.*
  do
  echo dir
  cd dir
  echo migrate-n parmfile
  cd ..
done

```

# 2 Bat R Throw L
The following three questions will be based on this dataset that describes statistics for Major League Baseball in 2008. Please paste in your one line of code, and the resulting R output into the response box.

How many National League baseball players batted right and threw with their left in 2008?